eventPlanner/urls.py
from django.contrib import admin
from django.urls import path
from eventplannerdb.views.events.event_views import (
    EventListView,
    EventDetailView,
    SpeakerDetailView,
    SurveyCreateView,
    EventAgendaCreateView,
    register_for_event,
    deregister_from_event,
    check_in_to_event,
)
from eventplannerdb.views.auth.auth_views import (
    LoginView,
    LogoutView,
    SignupView,
)

urlpatterns = [
    path("admin/", admin.site.urls),
    path("events/", EventListView.as_view(), name="event_list"),
    path("events/<int:pk>/", EventDetailView.as_view(), name="event_detail"),
    path("events/<int:event_id>/register/", register_for_event, name="register_for_event"),
    path("events/<int:event_id>/deregister/", deregister_from_event, name="deregister_from_event"),
    path("events/<int:event_id>/checkin/", check_in_to_event, name="check_in_to_event"),
    path("speaker/<int:pk>/", SpeakerDetailView.as_view(), name="speaker_detail"),
    path("survey/create/", SurveyCreateView.as_view(), name="survey_create"),
    path("agenda/create/", EventAgendaCreateView.as_view(), name="agenda_create"),
    path("", LoginView.as_view(), name="login"),
    path("logout/", LogoutView.as_view(), name="logout"),
    path("signup/", SignupView.as_view(), name="signup"),
]

eventplannerdb/models.py
from django.db import models
from django.contrib.auth.models import User

CHOICES = [
    (1, "Not Satisfied"),
    (2, "Somewhat Satisfied"),
    (3, "Neutral"),
    (4, "Satisfied"),
    (5, "Very Satisfied"),
]


class Event(models.Model):
    title = models.CharField(max_length=255)
    location = models.CharField(max_length=255)
    startDateTime = models.DateTimeField()
    endDateTime = models.DateTimeField()
    description = models.TextField(default="")
    speakers = models.ManyToManyField("Speaker", related_name="events")
    sponsors = models.ManyToManyField("Sponsor", related_name="events")
    registered_users = models.ManyToManyField(User, related_name="registered_events", blank=True)
    checkedIn_users = models.ManyToManyField(User, through="CheckIn",
                                              related_name="checkedIn_events", blank=True)


class CheckIn(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    event = models.ForeignKey(Event, on_delete=models.CASCADE)
    checkin_time = models.DateTimeField(auto_now_add=True)


class Speaker(models.Model):
    firstName = models.CharField(max_length=255)
    lastName = models.CharField(max_length=255)
    age = models.IntegerField()
    profession = models.CharField(max_length=255)
    contactNumber = models.CharField(max_length=255, default="")
    email = models.EmailField(default="")
    bio = models.TextField()
    icon = models.CharField(max_length=255, default="")


class Sponsor(models.Model):
    name = models.CharField(max_length=255)
    website = models.URLField(default="")
    companyLogo = models.CharField(max_length=255, default="")


class Agenda(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="agenda")
    title = models.CharField(max_length=255)
    start_time = models.DateTimeField()
    end_time = models.DateTimeField()


class Survey(models.Model):
    event = models.ForeignKey(Event, on_delete=models.CASCADE, related_name="surveys")
    title = models.CharField(max_length=255, default="")
    methodology = models.TextField(default="")
    is_anonymous = models.BooleanField(default=True)
    is_active = models.BooleanField(default=True)


class SurveyQuestion(models.Model):
    survey = models.ForeignKey(Survey, on_delete=models.CASCADE, related_name="questions")
    question = models.CharField(max_length=500, default="")
    CHOICES = CHOICES


class SurveyResponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    survey_question = models.ForeignKey("SurveyQuestion", on_delete=models.CASCADE)
    response = models.IntegerField(choices=CHOICES)

eventplannerdb/forms.py
# yourapp/forms.py
from django import forms
from .models import Survey


class SurveyForm(forms.ModelForm):
    class Meta:
        model = Survey
        fields = ["event", "title"]

eventplannerdb/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.views import View
from django.views.generic import ListView, DetailView, CreateView
from .models import Event, Survey, Speaker, EventAgenda
from .forms import SurveyForm
from django.contrib.auth import login, logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from django.views import View
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm


class EventListView(ListView):
    model = Event
    template_name = "event_list.html"
    context_object_name = "events"

    def get(self, request):
        # Get Query search from search input
        query = request.GET.get("searchInput")
        # Filter on Events
        if query:
            events = Event.objects.filter(title__icontains=query)
        else:
            events = Event.objects.all()
            query = "" # empty query if no search input is given
        # Render needed Data and View
        return render(request, "event_list.html", {"events": events, "query": query})


class EventDetailView(DetailView):
    model = Event
    template_name = "event_detail.html"
    context_object_name = "event"

@login_required  # Ensure the user is logged in to register
def register_for_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)

    if request.user not in event.registered_users.all():
        event.registered_users.add(request.user)
        event.save()

    return redirect('event_detail', pk=event_id)

@login_required
def deregister_from_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)

    if request.user in event.registered_users.all():
        event.registered_users.remove(request.user)
    
    if request.user in event.checkedIn_users.all():
        event.checkedIn_users.remove(request.user)
    
    event.save()
    
    return redirect('event_detail', pk=event_id)

@login_required
def check_in_to_event(request, event_id):
    event = get_object_or_404(Event, pk=event_id)

    if request.user not in event.checkedIn_users.all():
        event.checkedIn_users.add(request.user)
        event.save()
    
    return redirect('event_detail', pk=event_id)

class SpeakerDetailView(DetailView):
    model = Speaker
    template_name = "speaker_detail.html"
    context_object_name = "speaker"

class SurveyCreateView(CreateView):
    model = Survey
    form_class = SurveyForm
    template_name = "survey_form.html"
    success_url = "/events/"  # Redirect to the event list after survey creation


class EventAgendaCreateView(CreateView):
    model = EventAgenda
    fields = ["event", "title", "start_time", "end_time"]
    template_name = "eventagenda_form.html"
    success_url = "/events/"  # Redirect to the event list after agenda creation

class LoginView(View):
    def get(self, request):
        form = AuthenticationForm()
        return render(request, "login.html", {"form": form})

    def post(self, request):
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            return redirect("event_list")
        return render(request, "login.html", {"form": form})


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect("login")


class SignupView(View):
    def get(self, request):
        form = UserCreationForm()
        return render(request, "signup.html", {"form": form})

    def post(self, request):
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect("event_list")
        return render(request, "signup.html", {"form": form})

eventplannerdb/templates/base.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="en">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1.0" name="viewport"/>
  <title>
   {% block title %}JJF's Event Planner{% endblock %}
  </title>
  <link href="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.0/semantic.min.css" rel="stylesheet"/>
  <link href="https://cdn.jsdelivr.net/npm/@event-calendar/build@2.6.1/event-calendar.min.css" rel="stylesheet"/>
  <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css"/>
  <link href="{% static 'css/common.css' %}" rel="stylesheet" type="text/css"/>
   <style>
    body {
            background-color: white;
            body > .grid {
                height: 100%;
            }
            .column {
                max-width: 450px;
        }
        nav {
            background-color: #333;
            color: white;
            padding: 10px;
        }
        nav a {
            color: white;
            text-decoration: none;
            padding: 10px;
        }
   </style>
  </link>
 </head>
 <body>
  {% if user.is_authenticated %}
  <div class="ui secondary pointing menu">
   <a class="item" href="{% url 'event_list' %}">
    Events
   </a>
   {% if not user.is_authenticated %}
   <a class="ui item" href="{% url 'login' %}">
    Login
   </a>
   <a class="ui item" href="{% url 'signup' %}">
    Signup
   </a>
   {% endif %}
   <div class="right menu">
    {% if user.is_authenticated %}
    <a class="ui item" href="{% url 'logout' %}">
     Logout
    </a>
    {% endif %}
   </div>
  </div>
  {% endif %}
  <script src="https://code.jquery.com/jquery-3.6.4.min.js">
  </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/fomantic-ui/2.9.0/semantic.min.js">
  </script>
  <script src="https://cdn.jsdelivr.net/npm/@event-calendar/build@2.6.1/event-calendar.min.js">
  </script>
  <div>
   {% block content %}
    {# Content from child templates will be inserted here #}
  {% endblock %}
  </div>
 </body>
</html>

eventplannerdb/templates/event_detail.html
<!-- event_detail.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
<!-- Include Fomantic UI toast using messages rendered by backend -->
{% if messages %}
{% for message in messages %}
<script>
 $.toast({
    class: '{{ message.tags }}',
    position: 'bottom right',
    message: '{{ message }}'
  })
  ;
</script>
{% endfor %}
{% endif %}
<!-- Represents an Icon and Text to describe the view -->
<div class="ui stackable grid container">
 <div class="sixteen wide column centered">
  <h5 class="ui center aligned icon header">
   <i class="large file alternate outline icon">
   </i>
   <span>
    Event Details
   </span>
  </h5>
 </div>
</div>
<!-- Represents the Event Details Segments with 3 Tabs (Details, Administration, Agenda) -->
<div class="ui container">
 <h2 class="ui header">
  {{ event.title }}
 </h2>
 <div class="ui top attached tabular menu">
  <a class="item active" data-tab="event-details">
   Overview
  </a>
  {% if request.user.is_superuser and event.registered_users.exists  %}
  <a class="item" data-tab="event-admin">
   Administration
  </a>
  {% endif  %}
  <a class="item" data-tab="agenda">
   Agenda
  </a>
 </div>
 <div class="ui bottom attached tab segment active" data-tab="event-details">
  <div class="ui segments">
   <div class="ui segment">
    <h3 class="ui header">
     Event Details
    </h3>
    <p>
     <strong>
      Location:
     </strong>
     {{ event.location }}
    </p>
    <p>
     <strong>
      Description:
     </strong>
     {{ event.description }}
    </p>
    <p>
     <strong>
      Start Time:
     </strong>
     {{ event.startDateTime }}
    </p>
    <p>
     <strong>
      End Time:
     </strong>
     {{ event.endDateTime }}
    </p>
   </div>
   <div class="ui segment">
    <h3 class="ui header">
     Speakers
    </h3>
    <div class="ui list">
     {% for speaker in event.speakers.all %}
     <div class="item">
      <img alt="{{ speaker.firstName }} {{ speaker.lastName }} Avatar" class="ui avatar image" src="{% static 'images/speaker/'|add:speaker.icon %}"/>
      <div class="content">
       <strong>
        {{ speaker.firstName }} {{ speaker.lastName }}
       </strong>
       <p>
        {{ speaker.bio }}
       </p>
      </div>
     </div>
     {% endfor %}
    </div>
   </div>
   <div class="ui segment">
    <h3 class="ui header">
     Sponsors
    </h3>
    <div class="ui list">
     {% for sponsor in event.sponsors.all %}
     <div class="item">
      <img alt="{{ sponsor.name }} Logo" class="ui avatar image" src="{% static 'images/company/'|add:sponsor.companyLogo %}"/>
      <div class="content">
       <strong>
        {{ sponsor.name }}
       </strong>
       <p>
        Website:
        <a href="{{ sponsor.website }}">
         {{ sponsor.website }}
        </a>
       </p>
      </div>
     </div>
     {% endfor %}
    </div>
   </div>
   <!-- Actions Segment -->
   <div class="ui segment">
    <h3 class="ui header">
     Actions
    </h3>
    <div class="ui buttons">
     <!-- Registration and De-registration Buttons -->
     {% if request.user not in event.registered_users.all %}
     <form action="{% url 'register_for_event' event.id %}" id="registrationForm" method="post">
      {% csrf_token %}
      <button class="ui primary button" id="registerButton" type="submit">
       <i class="icon sign in">
       </i>
       Register for the Event
      </button>
     </form>
     <script>
      // JavaScript to handle loading indicator
        $('#registrationForm').submit(function() {
            $('#registerButton').addClass('loading');
        });
     </script>
     {% else %}
                     {% if request.user not in event.checkedIn_users.all %}
     <form action="{% url 'check_in_to_event' event.id %}" id="checkInForm" method="post">
      {% csrf_token %}
      <button class="ui primary button" id="checkInButton" type="submit">
       <i class="icon check square outline">
       </i>
       Check-In
      </button>
     </form>
     <div class="or">
     </div>
     {% endif %}
     <form action="{% url 'deregister_from_event' event.id %}" class="" id="deregistrationForm" method="post">
      {% csrf_token %}
      <button class="ui negative button" id="deregisterButton" type="submit">
       <i class="icon sign out">
       </i>
       Deregister from the Event
      </button>
     </form>
     <script>
      // JavaScript to handle loading indicator
        $('#deregistrationForm').submit(function() {
            $('#deregisterButton').addClass('loading');
        });
        $('#checkInForm').submit(function() {
            $('#checkInButton').addClass('loading');
        });
     </script>
     {% endif %}
    </div>
   </div>
  </div>
 </div>
 <div class="ui bottom attached tab segment" data-tab="event-admin">
  <!-- List of Checked-in Users (visible only to superadmins) -->
  {% if request.user.is_superuser and event.registered_users.exists  %}
  <div class="ui divider">
  </div>
  <div class="ui grid">
   <div class="eight wide column ml10 mb20">
    <div class="ui segment">
     <h3 class="ui header">
      Registered Users
     </h3>
     <div class="ui list">
      {% for user in event.registered_users.all %}
      <div class="item">
       {{ user.username }} | checked-in? 
       {% if user in event.checkedIn_users.all %}
       <i class="check icon" style="color:green;">
       </i>
       <!-- Green check icon -->
       {% else %}
       <i class="times icon" style="color:red;">
       </i>
       <!-- Red x icon -->
       {% endif %}
      </div>
      {% endfor %}
     </div>
    </div>
   </div>
   <!-- List of Checked-in Users (visible only to superadmins) -->
   {% if request.user.is_superuser and event.checkedIn_users.exists  %}
   <div class="eight wide column">
    <div class="ui segment">
     <h3 class="ui header">
      Checked-in Users
     </h3>
     <div class="ui list">
      {% for checkin in event.checkin_set.all %}
      <div class="item">
       <strong>
        {{ checkin.user.username }}
       </strong>
       - Check-in Time: {{ checkin.checkin_time }}
      </div>
      {% endfor %}
     </div>
    </div>
   </div>
  </div>
  {% endif %}
 </div>
 {% endif %}
 <div class="ui bottom attached tab segment" data-tab="agenda" style="height: 600px;">
  <div class="ui grid">
   <div class="row">
    <div class="sixteen wide column centered">
     <h5 class="ui center aligned icon header">
      Event Time: {{ event.startDateTime|date:"Y-m-d" }}
     </h5>
    </div>
   </div>
  </div>
  <div id="calendar">
  </div>
 </div>
 <script>
  // Initialize calendar view
   let ec = new EventCalendar(document.getElementById('calendar'), {
      view: 'listWeek',
      events: [
          {% for item in event.agenda.all %}
          { 
              editable: false,
              title: '{{ item.title }}',
              start: '{{ item.start_time|date:"Y-m-d\TH:i:s" }}',
              end: '{{ item.end_time|date:"Y-m-d\TH:i:s" }}',
              backgroundColor: '#B29DD9' // Set event color
          },
        {% endfor %}
      ]
  });
  // Change the current date
  ec.setOption('date', '{{ event.startDateTime|date:"Y-m-d" }}');
 </script>
</div>
<script>
 // Activate tab switching behavior
    $('.menu .item').tab();
</script>
{% endblock %}

eventplannerdb/templates/event_list.html
<!-- event_list.html -->
{% extends 'base.html' %}
{% load static %}


{% block content %}
<div class="ui stackable grid container">
 <!-- Row containing Logo and Page Name-->
 <div class="row">
  <div class="sixteen wide column centered">
   <h5 class="ui center aligned icon header">
    <i class="large calendar alternate outline icon">
    </i>
    <span>
     Events
    </span>
   </h5>
  </div>
 </div>
 <!-- Row containing search bar-->
 <div class="row">
  <div class="ten wide column centered">
  </div>
  <div class="six wide column right aligned" style="margin-right: 20px;">
   <div class="ui search">
    <form action="{% url 'event_list' %}" class="ui icon input" method="get">
     <input class="prompt" name="searchInput" placeholder="Search events..." type="text" value="{{ query }}"/>
     <i class="search icon">
     </i>
    </form>
   </div>
  </div>
 </div>
 <!-- Row containing list items of events-->
 <div class="row">
  <div class="sixteen wide column centered">
   <div class="ui relaxed celled divided list">
    {% if events %}
          {% for event in events %}
    <div class="item">
     <div class="right floated content">
      <a class="header" href="{% url 'event_detail' pk=event.pk %}">
       <button class="circular ui icon button" data-position="top center" data-tooltip="See more details">
        <i class="eye icon">
        </i>
       </button>
      </a>
     </div>
     <div class="content">
      <a class="header" href="{% url 'event_detail' pk=event.pk %}">
       {{ event.title }}
      </a>
      <div class="location mt10">
       Location: {{ event.location }}
      </div>
      <div class="meta mt10">
       {{ event.startDateTime }} - {{ event.endDateTime }}
      </div>
      {% if event.speakers %}
      <div class="mt10 mb10">
       <span>
        Speakers:
       </span>
       {% for speaker in event.speakers.all %}
       <div class="ui very relaxed horizontal list">
        <div class="item ml10">
         <img class="ui avatar image" src="{% static 'images/speaker/'|add:speaker.icon %}"/>
         <div class="content">
          <a class="header" href="{% url 'speaker_detail' pk=speaker.pk %}">
           {{ speaker.firstName }} {{ speaker.lastName }}
          </a>
         </div>
        </div>
       </div>
       {% endfor %}
      </div>
      {% endif %}
     </div>
    </div>
    {% endfor %}
          {% else %}
    <p class="ui center aligned">
     No events found.
    </p>
    {% endif %}
   </div>
  </div>
 </div>
</div>
{% endblock %}

eventplannerdb/templates/eventagenda_form.html
<!-- eventagenda_form.html -->
{% extends 'base.html' %}

{% block content %}
<h2>
 Create Event Agenda
</h2>
<form enctype="multipart/form-data" method="post">
 {% csrf_token %}
    {{ form.as_p }}
 <button type="submit">
  Submit
 </button>
</form>
{% endblock %}

eventplannerdb/templates/login.html
<!-- login.html -->
{% extends 'base.html' %}

{% block content %}
<div class="ui middle aligned center aligned grid logo">
 <div class="column">
  <h2 class="ui purple" style="margin-top: 30%">
   <img class="ui large circular image" src="static/images/logo.png"/>
   <div class="content" style="margin-top: 10px; margin-bottom: 30px;">
    Log-in to your account
   </div>
  </h2>
  <form action="{% url 'login' %}" class="ui large form" method="post">
   {% csrf_token %}
   <div class="ui stacked segment">
    {% for field in form %}
    <div class="form-field">
     {{ field.label_tag }} {{ field }}
     {% if field.errors %}
     <div class="ui error message">
      {{ field.errors|striptags }}
     </div>
     {% endif %}
    </div>
    {% endfor %}
   </div>
   <input class="ui fluid large purple submit button" type="submit" value="Submit"/>
   <div class="ui message">
    New to us?
    <a href="{% url 'signup' %}">
     Sign Up
    </a>
   </div>
  </form>
 </div>
</div>
{% endblock %}

eventplannerdb/templates/logout.html
<!-- logout.html -->
{% extends 'base.html' %}

{% block content %}
<h2>
 Logout
</h2>
<p>
 You have been logged out.
</p>
{% endblock %}

eventplannerdb/templates/signup.html
<!-- signup.html -->
{% extends 'base.html' %}

{% block content %}
<h2>
 Signup
</h2>
<form method="post">
 {% csrf_token %}
    {{ form.as_p }}
 <button type="submit">
  Signup
 </button>
</form>
{% endblock %}

eventplannerdb/templates/speaker_detail.html
<!-- speaker_detail.html -->
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="ui grid container">
 <div class="row">
  <div class="sixteen wide column centered">
   <div class="ui segment ml10 mr10">
    <h1>
     {{ speaker.firstName }} {{ speaker.lastName }}
    </h1>
    <p>
     Age: {{ speaker.age }}
    </p>
    <p>
     Profession: {{ speaker.profession }}
    </p>
    <p>
     Contact Number: {{ speaker.contactNumber }}
    </p>
    <p>
     Email: {{ speaker.email }}
    </p>
    <p>
     Bio: {{ speaker.bio }}
    </p>
    <img alt="{{ speaker.firstName }} {{ speaker.lastName }} Avatar" class="ui avatar image" src="{% static 'images/speaker/'|add:speaker.icon %}"/>
   </div>
  </div>
 </div>
</div>
{% endblock %}

eventplannerdb/templates/survey_form.html
<!-- survey_form.html -->
{% extends 'base.html' %}

{% block content %}
<h2>
 Create Survey
</h2>
<form enctype="multipart/form-data" method="post">
 {% csrf_token %}
    {{ form.as_p }}
 <button type="submit">
  Submit
 </button>
</form>
{% endblock %}